server {
    listen 80;
    listen 443 ssl;

    server_name izan.test www.izan.test;

    root "C:\\nginx\\html";

    ssl_certificate "C:\\nginx\\ssl\\izan.test.crt";
    ssl_certificate_key "C:\\nginx\\ssl\\izan.test.key";

    ssl_protocols TLSv1 TLSv1.1 TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5; 

    index index.html;

    location / {
        try_files $uri $uri/ =404;

        satisfy all;

        allow 127.0.0.1;
        deny all;

        auth_basic "Acceso restringido";
        auth_basic_user_file "C:\\nginx\\htpasswd\\.htpasswd";
    }

    location /api {
        satisfy all;

        allow 192.168.1.0/24;
        allow 127.0.0.1;
        deny all;

        auth_basic "Zona segura";
        auth_basic_user_file "C:\\nginx\\htpasswd\\.htpasswd";
    }
}